# [START django_app]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT API.wsgi

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

beta_settings:
    cloud_sql_instances: personal-252216:us-east1:site-instance

includes:
 - env_variables.yaml
